### ISSUE TITLE
[FEATURE/QUESTION] Change disable variable to enable

### ISSUE THREAD

**Issue by tabacha** [UdelaRInterior/ansible-role-jitsi-meet#15]
**Is your feature request related to a problem? Please describe.**

I think it is not good style to name boolean variable in a negative meaning like this:

```jitsi_meet_disable_third_party_requests: true```

it is confusing to the admin/user because he must set it to true to disalbe a feature.

I suggest to change all variable name to th positiv menaing, for example:

```jitsi_meet_enable_third_party_requests: false```

On the other side, a user see a setting in a howto and perhabs did not find it in our ansible role if it is named different. 

**This will affect the follwoing names / suggested new name:**

* jitsi_meet_disable_third_party_requests -> jitsi_meet_enable_third_party_requests
* jitsi_meet_desktop_sharing_chrome_disabled ->  jitsi_meet_enable_desktop_sharing_chrome
* jitsi_meet_desktop_sharing_firefox_disabled ->  jitsi_meet_enable_desktop_sharing_firefox
* jitsi_meet_disable_video_background -> jitsi_meet_show_video_background
* jitsi_meet_disable_audio_levels -> jitsi_meet_show_audio_levels

**Comment by santiagomr** [comment]
I agree that the name of the variables makes you think twice before choosing the desired value.

I like all the names you suggest. Respecting the default values with which Jitsi Meet is installed, any improvement in intuitiveness is welcome.

Do you want to send a PR with them?

**Comment by tabacha** [comment]
HI @santiagomr  I will perpare a PR soon

**Comment by santiagomr** [comment]
Thanks for sending the PR (#17), it's already merged into master
