### ISSUE TITLE
[BUG] Ansible-lint 701 author should be a string

### ISSUE THREAD

**Issue by tabacha** [UdelaRInterior/ansible-role-jitsi-meet#18]
**Describe the bug**
ansible-lint gives a warning on meta/main.yml: 

```
[701] author should be a string
meta/main.yml:2
{'meta/main.yml': {'galaxy_info': {'role_name': 'jitsi_meet', 'author': ['@ageis', '@conorsch', '@santiagomr'], 'description': 'Installs Jitsi Meet videoconferencing software', 'company': ['@freedomofpress', '@UdelaRInterior'], 'license': 'MIT', 'min_ansible_version': 2.7, 'platforms': [{'name': 'Debian', 'versions': ['jessie', 'stretch', 'buster'], '__line__': 15, '__file__': '/home/sven/src/adfc/adfc-hamburg.jitsi_meet/meta/main.yml'}, {'name': 'Ubuntu', 'versions': ['bionic'], '__line__': 20, '__file__': '/home/sven/src/adfc/adfc-hamburg.jitsi_meet/meta/main.yml'}], 'galaxy_tags': ['system', 'webconference', 'jitsi', 'talk', 'chat'], '__line__': 3, '__file__': '/home/sven/src/adfc/adfc-hamburg.jitsi_meet/meta/main.yml'}, 'dependencies': [], '__line__': 2, '__file__': '/home/sven/src/adfc/adfc-hamburg.jitsi_meet/meta/main.yml', 'skipped_rules': []}}
```

**To Reproduce**

```
pip install ansible-lint

ansible-lint /path/to/repo
```

I do not konw if this is an ansible-lint error or a error in this role.

I have prepared a github-action to run ansible-lint on every pull-request:

https://github.com/ADFC-Hamburg/ansible-role-jitsi-meet/runs/658539760?check_suite_focus=true

**Comment by santiagomr** [comment]
It was an error in the meta/main.yml file. The `author` field was detailed as a list of strings and only a single string is accepted. I already fixed this on `master`.

I was inspired by your github-action to add a similar one to this role, for now just running ansible-lint. As I mentioned in #19, the molecule tests are outdated.
