### ISSUE TITLE
branch naming 

### ISSUE THREAD

**Issue by kamihacker** [UdelaRInterior/ansible-role-jitsi-meet#4]
if you add a CONTRIBUTING file it would be easier to know:

- desired roadmap 
- what is the stable branch to implement in a production environment
- how to contribute code to a particular feature branch
- definition of done for each feature branch

**Comment by santiagomr** [comment]
Hello @kamihacker, thanks for the comment. We agree that it would be better to have a CONTRIBUTING file.

We will add it soon. For now we tell you that:
- The branch considered stable for production environments is `master`
- The new features are worked from issues (they will specify the branch to be used).
- All PR are welcome in the corresponding branch.
